// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TesoreriaMargaritas.Data;

#nullable disable

namespace TesoreriaMargaritas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224090000_AddAnuladoEntradas")]
    partial class AddAnuladoEntradas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // ... (Metadata básica)
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            // El resto se infiere del snapshot
        }
    }
}