// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesoreriaMargaritas.Data;

#nullable disable

namespace TesoreriaMargaritas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116210921_PermitirObservacionesNulasEnArqueo")]
    partial class PermitirObservacionesNulasEnArqueo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesoreriaMargaritas.Models.Arqueo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseCaja")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CajaId")
                        .HasColumnType("int");

                    b.Property<string>("ConteoBilletesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DescuadreDaviplata")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DescuadreEfectivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DescuadreNequi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("FechaArqueo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FisicoEfectivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReportadoDaviplata")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ReportadoNequi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaldoArrastreAnterior")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaldoInicialEfectivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistEntradasDaviplata")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistEntradasEfectivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistEntradasNequi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistSalidasDaviplata")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistSalidasEfectivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistSalidasNequi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistTotalDaviplata")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistTotalEfectivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SistTotalNequi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Arqueos");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<int?>("ArqueoId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ArqueoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<int?>("ArqueoId")
                        .HasColumnType("int");

                    b.Property<string>("Beneficiario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Consecutivo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ArqueoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Proveedor", b =>
                {
                    b.Property<string>("CODPROVEEDOR")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NOMPROVEEDOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODPROVEEDOR");

                    b.ToTable("PROVEEDORES");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.SecuenciaPrefijo", b =>
                {
                    b.Property<string>("Prefijo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UltimoConsecutivo")
                        .HasColumnType("int");

                    b.HasKey("Prefijo");

                    b.ToTable("SecuenciasPrefijos");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Usuario", b =>
                {
                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NumeroDocumento");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Vendedor", b =>
                {
                    b.Property<string>("CODVENDEDOR")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NOMVENDEDOR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODVENDEDOR");

                    b.ToTable("VENDEDORES");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Arqueo", b =>
                {
                    b.HasOne("TesoreriaMargaritas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Entrada", b =>
                {
                    b.HasOne("TesoreriaMargaritas.Models.Arqueo", "Arqueo")
                        .WithMany()
                        .HasForeignKey("ArqueoId");

                    b.HasOne("TesoreriaMargaritas.Models.Usuario", "Usuario")
                        .WithMany("EntradasRegistradas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arqueo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Gasto", b =>
                {
                    b.HasOne("TesoreriaMargaritas.Models.Arqueo", "Arqueo")
                        .WithMany()
                        .HasForeignKey("ArqueoId");

                    b.HasOne("TesoreriaMargaritas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arqueo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TesoreriaMargaritas.Models.Usuario", b =>
                {
                    b.Navigation("EntradasRegistradas");
                });
#pragma warning restore 612, 618
        }
    }
}
