// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using TesoreriaMargaritas.Data;

#nullable disable

namespace TesoreriaMargaritas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113210300_AddObservacionesToEntradas")]
    partial class AddObservacionesToEntradas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            // El resto se infiere
        }
    }
}